"""The launcher preflight condition that decides whether to check X11 libraries.

The launcher is generated by `packaging/linux/build_bundle.sh` into a heredoc, so
it is not a file that can be imported or linted. These tests lift the condition
out of that heredoc, undo the heredoc's own escaping the way bash would, and run
it -- so the thing under test is the text that actually ships.
"""

from __future__ import annotations

from pathlib import Path
import shutil
import subprocess

import pytest

BUILD_SCRIPT = Path(__file__).resolve().parents[1] / "packaging" / "linux" / "build_bundle.sh"

pytestmark = pytest.mark.skipif(shutil.which("bash") is None, reason="needs bash")


def _preflight_condition() -> str:
    """Return the shipped `if [[ ... ]]` condition, unescaped as bash would."""

    lines = BUILD_SCRIPT.read_text(encoding="utf-8").splitlines()
    start = next(i for i, line in enumerate(lines) if "MLP_SKIP_LIBRARY_CHECK:-0" in line)
    end = next(i for i in range(start, len(lines)) if lines[i].rstrip().endswith("]]; then"))
    block = "\n".join(lines[start : end + 1])
    # The heredoc opens with an unquoted `EOF`, so bash strips exactly these.
    unescaped = block.replace("\\$", "$").replace("\\`", "`").replace("\\\\", "\\")
    return unescaped.removeprefix("if ").removesuffix("; then")


def _check_runs(**env: str) -> bool:
    """True when the preflight would run its library check in this environment."""

    script = f"if {_preflight_condition()}; then echo RAN; else echo SKIPPED; fi"
    # A clean environment: inheriting the test runner's DISPLAY/WAYLAND_DISPLAY
    # would make the result depend on whoever ran pytest.
    completed = subprocess.run(
        ["bash", "-euo", "pipefail", "-c", script],
        capture_output=True,
        text=True,
        env={"PATH": "/usr/bin:/bin", **env},
        check=True,
    )
    return completed.stdout.strip() == "RAN"


def test_an_x11_session_gets_the_check() -> None:
    """The case the check exists for."""

    assert _check_runs(DISPLAY=":0") is True


def test_a_wayland_session_advertised_only_by_wayland_display_is_skipped() -> None:
    """The defect: WSLg, bare compositors, `su`, and systemd-user launches set
    WAYLAND_DISPLAY but leave XDG_SESSION_TYPE unset. Testing the latter alone
    ran the check on a session that uses none of these libraries, so a host
    without the X11 helpers was blocked from an app that would have started."""

    assert _check_runs(DISPLAY=":0", WAYLAND_DISPLAY="wayland-0") is False


def test_a_wayland_session_advertised_by_session_type_is_skipped() -> None:
    assert _check_runs(DISPLAY=":0", XDG_SESSION_TYPE="wayland") is False


def test_no_display_at_all_is_skipped() -> None:
    """Headless: Qt will pick offscreen/minimal, or fail on its own terms."""

    assert _check_runs() is False


def test_the_documented_escape_hatch_skips_the_check() -> None:
    assert _check_runs(DISPLAY=":0", MLP_SKIP_LIBRARY_CHECK="1") is False


def test_the_escape_hatch_is_exact() -> None:
    """`MLP_SKIP_LIBRARY_CHECK=0` and other values must not disable the check."""

    assert _check_runs(DISPLAY=":0", MLP_SKIP_LIBRARY_CHECK="0") is True
    assert _check_runs(DISPLAY=":0", MLP_SKIP_LIBRARY_CHECK="yes") is True
